### ISSUE TITLE
REWASD not working to turn REMAP on, reinstalled the program and did everything right still doesn't work.

### ISSUE THREAD

**Issue by OminousWeyland** [EugeneSunrise/reWASD#23]
I reinstalled the program like 10 times.

**Comment by EugeneSunrise** [comment]
> I reinstalled the program like 10 times.

Bro, if you did everything right, everything would work ;D, 

Start reWasdEngine only from dnspy, like in video

You should have 4 breakpoints in the dnspay (in video only 1 because the fix came out today)

If you do everything as in the video, everything will work for you

**Comment by SadewJay** [comment]
it is working perfectly...

**Comment by AyeeSecret** [comment]
It doesn't let me turn remap on, breakpoints aren't working on dnspy

**Comment by EugeneSunrise** [comment]
> It doesn't let me turn remap on, breakpoints aren't working on dnspy

What do you mean they don't work? Are they not imported?

**Comment by AyeeSecret** [comment]
Applying any config just doesn't work

**Comment by EugeneSunrise** [comment]
> Applying any config just doesn't work
> 
> 
> 
> 

Applying any config doesnt work because you not imported breakpoints😤

**Comment by AyeeSecret** [comment]
> > Applying any config just doesn't work
> 
> Applying any config doesnt work because you not imported breakpoints😤

Yeah thats my issue, I can't import any breakpoints in DnSpy, it doesn't show up. Am I missing anything?

**Comment by EugeneSunrise** [comment]
> > > Applying any config just doesn't work
> 
> > 
> 
> > Applying any config doesnt work because you not imported breakpoints😤
> 
> 
> 
> Yeah thats my issue, I can't import any breakpoints in DnSpy, it doesn't show up. Am I missing anything? 

Yep, there may be two reasons why they are not imported:

1. You need to select the current assembly in dnSpy, that is, click on reWASDEngine in Assembly editor, I did it in the video at 2:15.

2. Change the paths to the file reWASDEngine.exe in the file with breakpoints (1337_pus...xml), there are only 4 lines where you need to set the correct path to the file, in the video it is 1:46 minute (also in the video there is only 1 path because today the fix came out and now there are 4)

**Comment by AyeeSecret** [comment]
#2 fixed it, I had downloaded the old version last night, and tried using that. Thanks bro!
